
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Footer } from '../components/Footer/Footer';
import { Header } from '../components/Header';
import { Proyects } from '../components/ProyectList';
import styles from '../styles/Home.module.css';
export default function Home() {

  // Code for prevent error render
  const [mounted, setMounted] = useState()
  useEffect(() => setMounted(true), [])
  if (!mounted) return null

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Portafolio | Fernando Mercado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>

        <Proyects />
      </main>
      <Footer/>

    </div>
  )
}
