
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { AboutMe } from '../components/About Me/AboutMe';
import { Footer } from '../components/Footer/Footer';
import { Header } from '../components/Header/Header';
import { MainComponent } from '../components/Main/MainComponent';
import { Proyects } from '../components/ProyectList';
export default function Home() {

  // Code for prevent error render
  const [mounted, setMounted] = useState()
  useEffect(() => setMounted(true), [])
  if (!mounted) return null


  return (
    <>
      <Head>
        <title>Portafolio | Fernando Mercado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main  className='py-20'>
        <MainComponent />
        <AboutMe/>
        <Proyects />
      </main>
      <Footer />

    </>
  )
}
