import { useTheme } from 'next-themes';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Header } from '../components/Header';
import { Proyects } from '../components/ProyectList';
import styles from '../styles/Home.module.css';
export default function Home() {
  const { theme, setTheme } = useTheme()
  const [mounted,setMounted]=useState()
  useEffect(()=>setMounted(true),[])
  
  const changeTheme = () => setTheme(theme === 'light' ? 'dark' : 'light')
  if(!mounted) return null
  return (
    <div className={styles.container}>
      <Head>
        <title>Portafolio | Fernando Mercado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header/>
      <main className={styles.main}>
        <button onClick={changeTheme} className='text-lg shadow-sm p-2 dark:bg-bunker dark:text-white'>Toggle Theme</button>
        <Proyects/>
      </main>


    </div>
  )
}
